---
#
# Tasks and roles for all hosts
#
- hosts: homeserver
  gather_facts: false

  # pre_tasks:
  #     - import_tasks: tasks/ssh_juggle_port.yml
  #       tags:
  #           - port

- hosts: homeserver
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: geerlingguy.security
        tags:
            - security

      - role: docker
        tags:
            - docker

      # - role: network/avahi
      #   tags:
      #       - avahi
      #   when: enable_avahi | default(false)

      - role: chriswayg.msmtp-mailer
        tags:
            - msmtp

      # - role: oefenweb.dns
      #   tags:
      #       - dns

      - role: geerlingguy.ntp
        tags:
            - ntp

      # - role: linux-system-roles.cockpit
      #   tags:
      #       - cockpit
      #   when: enable_cockpit | default(false)

      # #
      # # Security
      # #
      # - role: security/fail2ban
      #   tags:
      #       - fail2ban
      #   when: enable_fail2ban | default(false)

      # - role: security/iptables
      #   tags:
      #       - iptables
      #   when: enable_iptables | default(false)

      # - role: security/crowdsec
      #   tags:
      #       - crowdsec
      #   when: enable_crowdsec | default(false)

      - role: security/endlessh
        tags:
            - endlessh
        when: enable_endlessh | default(false)

      #
      # Network
      #
      - role: network/swag
        become: yes
        tags:
            - swag
            - containers

      # - role: network/bunkerized-nginx
      #   become: no
      #   tags:
      #       - bunkerized-nginx
      #       - containers
      #   when: enable_bunkerized_nginx | default(false)

      # - role: network/wireguard
      #   become: no
      #   tags:
      #       - wireguard
      #       - containers
      #   when: enable_wireguard | default(false)

      # - role: network/ikev2
      #   become: no
      #   tags:
      #       - ikev2
      #       - containers
      #   when: enable_ikev2 | default(false)

      # - role: network/ddclient
      #   become: yes
      #   when: enable_ddclient | default(false)
      #   tags:
      #       - ddclient

      # - role: network/duckdns
      #   become: no
      #   when: enable_duckdns | default(false)
      #   tags:
      #       - duckdns

      # - role: network/cloudflare-ddns
      #   become: no
      #   tags:
      #       - cloudflare-ddns
      #       - containers
      #   when: enable_cloudflare_ddns | default(false)

      # - role: network/adguard
      #   become: no
      #   tags:
      #       - adguard
      #       - containers
      #   when: enable_adguard | default(false)

      # #
      # # Filesystems
      # #
      # - role: filesystems/mergerfs
      #   become: yes
      #   tags:
      #       - mergerfs
      #   when: enable_nas_stuff | default(false)

      # - role: filesystems/mounts
      #   become: yes
      #   tags:
      #       - mounts
      #   when: enable_nas_stuff | default(false)

      # - role: filesystems/hd-idle
      #   become: yes
      #   tags:
      #       - hd-idle
      #   when: enable_nas_stuff | default(false)

      # - role: stuvusit.smartd
      #   become: yes
      #   tags:
      #       - smartd
      #   when: enable_nas_stuff | default(false)

      # - role: ironicbadger.snapraid
      #   become: yes
      #   tags:
      #       - snapraid
      #   when: enable_nas_stuff | default(false)

      #
      # Monitoring
      #
      - role: containers/monitoring/grafana
        become: no
        tags:
            - grafana
            - monitoring
            - containers
        when: enable_grafana | default(false)

      - role: containers/monitoring/prometheus
        become: no
        tags:
            - prometheus
            - monitoring
            - containers
        when: enable_prometheus | default(false)

      - role: geerlingguy.node_exporter
        tags:
            - node_exporter
            - monitoring
            - containers
        when: enable_node_exporter | default(false)

      # #
      # # Home automation
      # #
      # - role: containers/homeautomation/deconz
      #   tags:
      #       - deconz
      #       - smarthome
      #       - containers
      #   when: enable_deconz | default(false)

      # - role: containers/homeautomation/homeassistant
      #   become: no
      #   tags:
      #       - homeassistant
      #       - smarthome
      #       - containers
      #   when: enable_homeassistant | default(false)

      # - role: containers/homeautomation/mqtt
      #   become: no
      #   tags:
      #       - mqtt
      #       - smarthome
      #       - containers
      #   when: enable_homeassistant | default(false)
