---
container_name: coolify
coolify_root_dir: /data/coolify
coolify_source_dir: "{{ coolify_root_dir }}/source"
coolify_env_file: "{{ coolify_source_dir }}/.env"
coolify_install_script_url: https://cdn.coollabs.io/coolify/install.sh
coolify_auto_update: false
coolify_app_port: "8000"
coolify_soketi_port: "6001"
coolify_root_username: ""
coolify_root_user_email: ""
coolify_root_user_password: ""
