---
container_name: whisparr
whisparr_port: 6969
whisparr_image: ghcr.io/hotio/whisparr:v3
arr_network: arr-net
whisparr_media_dir: "{{ mergerfs_root }}/Media/Whisparr"
whisparr_download_dir: "{{ mergerfs_root }}/usenet/complete/whisparr"
whisparr_root_folder: /storage/Media/Whisparr
whisparr_sabnzbd_host: sabnzbd
whisparr_sabnzbd_port: 8080
whisparr_sabnzbd_category: whisparr
whisparr_prowlarr_url: http://prowlarr:9696
whisparr_prowlarr_base_url: http://whisparr:6969
whisparr_prowlarr_sync_categories:
  - 6000
  - 6010
  - 6020
  - 6030
  - 6040
  - 6045
  - 6050
  - 6060
  - 6070
  - 6080
  - 6090
whisparr_prowlarr_download_client_name: SABnzbd
whisparr_prowlarr_download_client_default_category: movies
whisparr_prowlarr_download_client_mapped_categories:
  - clientCategory: whisparr
    categories:
      - 6000
      - 6010
      - 6020
      - 6030
      - 6040
      - 6045
      - 6050
      - 6060
      - 6070
      - 6080
      - 6090
whisparr_authentication_method: none
whisparr_authentication_required: disabledForLocalAddresses
whisparr_search_studio_code: true
whisparr_search_title_only: true
whisparr_search_title_date: false
whisparr_search_studio_date: true
whisparr_search_studio_title: true
whisparr_search_date_format: yymmdd
whisparr_search_studio_format: clean
