---
- name: Ensure Prowlarr config dir exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    owner: "{{ username }}"
    group: users
    mode: '0775'

- name: Ensure arr Docker network
  docker_network:
    name: "{{ arr_network }}"
    state: present

- name: Make sure the Prowlarr container is running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/prowlarr:latest"
    pull: yes
    state: started
    networks:
      - name: "{{ arr_network }}"
    networks_cli_compatible: yes
    published_ports:
      - "127.0.0.1:{{ prowlarr_port }}:9696"
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
