---
# More info: https://docs.linuxserver.io/images/docker-plex
- name: Ensure Plex config and media directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: users
    mode: '0775'
  loop:
    - "{{ docker_dir }}/{{ container_name }}"
    - "{{ mergerfs_root }}/Media"
    - "{{ mergerfs_root }}/Media/TV"
    - "{{ mergerfs_root }}/Media/Movies"
    - "{{ mergerfs_root }}/Media/Music"

- name: Make sure the Plex container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/plex:latest"
    pull: yes
    state: started
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    groups:
      - "{{ gpu_render_gid }}"
      - "{{ gpu_video_gid }}"
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      VERSION: "docker"
      PLEX_CLAIM: "{{ plex_claim_token | default('') }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Media/Music:/music"
    restart_policy: unless-stopped
