---
# More information: https://www.home-assistant.io/installation/raspberrypi#docker-compose
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: 'homeassistant/home-assistant:stable'
      networks:
          - name: swag_internal_macvlan
            ipv4_address: '{{ ip_address }}'
      pull: yes
      state: 'started'
      env:
          'TZ': '{{ timezone }}'
      volumes:
          - '{{ docker_dir }}/{{ container_name }}/config:/config'
      restart_policy: unless-stopped
